-- Minha Cabeleira — expansão editorial do catálogo para o deploy de teste
-- Verificação editorial e de disponibilidade: 29/09/2026.
-- Objetivo: manter ao menos 3 opções nas categorias-base da rotina e
-- adicionar alternativas específicas para oleosidade/ressecamento do couro cabeludo.
--
-- IMPORTANTE:
-- - marca nunca é critério de recomendação;
-- - atributos descrevem a função técnica usada pelo motor;
-- - contraindicações e bloqueios de segurança continuam tendo prioridade;
-- - preços são referências verificadas na data acima e devem ser atualizados periodicamente;
-- - image_url não é sobrescrito em reexecuções, para preservar uploads feitos no admin.

insert into public.products (
  id, slug, brand, name, category, size,
  image_url, price, currency, retailer, product_url,
  price_checked_at, ingredients_raw, attributes,
  availability, source_url, verified_at, link_type
)
values
(
  'vult-choque-reconstrucao-shampoo-350ml',
  'vult-choque-reconstrucao-shampoo-350ml',
  'Vult',
  'Shampoo Cabelos Choque de Reconstrução',
  'shampoo',
  '350 ml',
  null,
  12.90,
  'BRL',
  'Vult',
  'https://www.vult.com.br/produto/shampoo-vult-cabelos-choque-de-reconstrucao-350ml',
  '2026-09-29',
  'Água; Lauriletersulfato de sódio; Cocoamidopropilbetaína; Cloreto de potássio; Glicerol; Fenoxietanol; Perfume; Benzoato de sódio; Dimeticonol; Diestearato de etilenoglicol; Ácido láctico; Gliconato de sódio; Cloreto de goma guar hidroxipropiltrimônio; Poliquatérnio-7; Lauromacrogol 400; Acetato de tocoferila; Dodecilbenzenosulfonato de trietanolamina; Ácido benzoico; Álcool benzílico; Polissorbato 20; Nicotinamida; Amido; Extrato de Cystoseira compressa; Hidróxido de sódio; Gluconolactona; Proteína de soja hidrolisada; Glúten de trigo hidrolisado; Proteína de milho hidrolisada; Extrato da semente de Ceratonia siliqua hidrolisado; Álcool feniletílico; Sorbato de potássio; Caprililglicol; Butilcarbamato de iodopropinila; Ácido deidroacético; Poliquatérnio-16; Gliconato de cálcio; Extrato da folha de Amaranthus hypochondriacus; Cumarina; Hexil cinamal; Limoneno; Linalol',
  array['damage_support'],
  'active',
  'https://www.vult.com.br/produto/shampoo-vult-cabelos-choque-de-reconstrucao-350ml',
  '2026-09-29',
  'editorial'
),
(
  'seda-hidratacao-diaria-shampoo-325ml',
  'seda-hidratacao-diaria-shampoo-325ml',
  'Seda',
  'Shampoo Hidratação Diária',
  'shampoo',
  '325 ml',
  null,
  12.36,
  'BRL',
  'Drogasil',
  'https://www.drogasil.com.br/shampoo-seda-hidratacao-diaria-325ml-1471599.html',
  '2026-09-29',
  'Água; Lauriletersulfato de sódio; Cocoamidopropilbetaína; Dimeticonol; Cloreto de sódio; Piritiona zíncica; Carbômer; Perfume; Fenoxietanol; Hidróxido de sódio; Salicilato de sódio; Cloreto de goma guar hidroxipropiltrimônio; Sulfato de zinco; Ácido cítrico; Cloridrato de arginina; Cloridrato de lisina; Óleo de melaleuca; Óleo de soja; Queratina hidrolisada; Azul brilhante; Polissorbato 20; Amarelo de quinolina laca de alumínio; Ácido ascórbico; Pantenol; Acetato de tocoferila; Biotina; Nicotinamida; Salicilato de benzila; Citronelol; Hexil cinamal; Limoneno; Linalol',
  array['moisture_support'],
  'active',
  'https://www.ingredientesunilever.com.br/p/seda-hidratacaoodiaria325ml-2024.html/17891150037458',
  '2026-09-29',
  'editorial'
),
(
  'vult-choque-reconstrucao-condicionador-200ml',
  'vult-choque-reconstrucao-condicionador-200ml',
  'Vult',
  'Condicionador Cabelos Choque de Reconstrução',
  'conditioner',
  '200 ml',
  null,
  17.90,
  'BRL',
  'Vult',
  'https://www.vult.com.br/produto/condicionador-vult-cabelos-choque-de-reconstrucao-200ml',
  '2026-09-29',
  'Água; Álcool cetearílico; Glicerol; Isoestearamidopropil dimetilamina; Dimeticonol; Cloreto de cetrimônio; Perfume; Ácido láctico; Fenoxietanol; Metossulfato de beentrimônio; Álcool benzílico; Gliconato de sódio; Hietelose; Acetato de tocoferila; Dodecilbenzenosulfonato de trietanolamina; Fosfato dissódico; Nicotinamida; Polissorbato 60; Hidróxido de sódio; Amido de milho; Poliuretano-39; Fosfato de sódio; Extrato de alga Cystoseira compressa; Gliconolactona; Proteína de soja hidrolisada; Butilcarbamato de iodopropinila; Extrato da semente de alfarroba hidrolisado; Proteína de milho hidrolisada; Glúten de trigo hidrolisado; Benzoato de sódio; Álcool feniletílico; Sorbato de potássio; Caprililglicol; Cloreto de guar hidroxipropiltrimônio; Ácido desidroacético; Poliquatérnio-16; Fenilpropanol; Poliquatérnio-7; Propanodiol; Extrato da folha do caruru-vermelho; Gliconato de cálcio; Tocoferol; Cumarina; Hexil cinamal; Limoneno; Linalol',
  array['conditioning', 'moisture_support', 'damage_support'],
  'active',
  'https://www.vult.com.br/produto/condicionador-vult-cabelos-choque-de-reconstrucao-200ml',
  '2026-09-29',
  'editorial'
),
(
  'seda-ceramidas-condicionador-325ml',
  'seda-ceramidas-condicionador-325ml',
  'Seda',
  'Condicionador Ceramidas',
  'conditioner',
  '325 ml',
  null,
  16.99,
  'BRL',
  'Drogasil',
  'https://www.drogasil.com.br/seda-condicionador-sos-ceramidas-325ml.html',
  '2026-09-29',
  'Água; Álcool cetoestearílico; Dimeticona; Cloreto de beentrimônio; Perfume; Ácido láctico; Estearamidopropil dimetilamina; Amodimeticona; Benzoato de sódio; Cloreto de sódio; Edetato dissódico; Colágeno hidrolisado; Vermelho 33; Ceramida NG; Retinol; Salicilato de benzila; Citronelol; Hexil cinamal; Linalol',
  array['conditioning', 'moisture_support', 'damage_support'],
  'active',
  'https://www.ingredientesunilever.com.br/p/seda-coceramidas325ml-2025.html/27891150037250',
  '2026-09-29',
  'editorial'
),
(
  'vult-choque-reconstrucao-mascara-250g',
  'vult-choque-reconstrucao-mascara-250g',
  'Vult',
  'Máscara Reconstrutora Cabelos Choque de Reconstrução',
  'mask',
  '250 g',
  null,
  17.90,
  'BRL',
  'Vult',
  'https://www.vult.com.br/produto/mascara-reconstrutora-vult-cabelos-choque-de-reconstrucao-250g',
  '2026-09-29',
  'Água; Álcool cetoestearílico; Palmitato de isopropila; Glicerol; Estearamidopropil dimetilamina; Cloreto de cetrimônio; Óleo de rícino; Perfume; Manteiga de Butyrospermum parkii; Ácido láctico; Metossulfato de beentrimônio; Fenoxietanol; Gliconato de sódio; Cloreto de goma guar hidroxipropiltrimônio; Acetato de tocoferila; Hidróxido de sódio; Nicotinamida; Amido; Poliuretano-39; Extrato de Cystoseira compressa; Gluconolactona; Proteína de soja hidrolisada; Álcool benzílico; Glúten de trigo hidrolisado; Proteína de milho hidrolisada; Extrato da semente de Ceratonia siliqua hidrolisado; Benzoato de sódio; Álcool feniletílico; Sorbato de potássio; Caprililglicol; Ácido deidroacético; Poliquatérnio-16; Propanodiol; Poliquatérnio-7; Fenilpropanol; Tocoferol; Gliconato de cálcio; Extrato da folha de Amaranthus hypochondriacus; Cumarina; Hexil cinamal; Limoneno; Linalol',
  array['conditioning', 'moisture_support', 'damage_support'],
  'active',
  'https://www.vult.com.br/produto/mascara-reconstrutora-vult-cabelos-choque-de-reconstrucao-250g',
  '2026-09-29',
  'editorial'
),
(
  'elseve-oleo-extraordinario-100ml',
  'elseve-oleo-extraordinario-100ml',
  'Elseve',
  'Óleo Extraordinário Nutrição',
  'oil',
  '100 ml',
  null,
  49.90,
  'BRL',
  'Drogasil',
  'https://www.drogasil.com.br/elseve-oleo-extraordinario-100ml-1318524.html',
  '2026-09-29',
  'Cyclopentasiloxane; Dimethiconol; Chamomilla Recutita Extract; Matricaria Flower Extract; Cocos Nucifera Oil; Coconut Oil; Nelumbium Speciosum Extract; Gardenia Tahitensis Flower Extract; Rosa Canina Flower Extract; Glycine Soja Oil; Parfum',
  array['conditioning', 'moisture_support', 'damage_support', 'heat_protection'],
  'active',
  'https://www.loreal-paris.com.br/elseve/oleo-extraordinario/oleo-extraordinario',
  '2026-09-29',
  'editorial'
),
(
  'seda-toque-de-seda-serum-oleo-60ml',
  'seda-toque-de-seda-serum-oleo-60ml',
  'Seda',
  'Sérum + Óleo de Tratamento Toque de Seda',
  'oil',
  '60 ml',
  null,
  21.99,
  'BRL',
  'Drogasil',
  'https://www.drogasil.com.br/seda-serum-oleo-tratamento-toque-de-seda-frasco-60ml-pump-1249844.html',
  '2026-09-29',
  'Decametilciclopentasiloxano; Parafina líquida; Dimeticonol; Perfume; Óleo da castanha de argan; Água; Seda hidrolisada; Alfa-isometil ionona; Amil cinamal; Salicilato de benzila; Citral; Citronelol; Cumarina; Geraniol; Hexil cinamal; Limoneno; Linalol; Ácido ascórbico; Pantenol; Acetato de tocoferila; Biotina; Nicotinamida',
  array['conditioning', 'moisture_support', 'damage_support'],
  'active',
  'https://www.ingredientesunilever.com.br/p/seda-toquedeseda60ml-2024.html/07891150101753',
  '2026-09-29',
  'editorial'
),
(
  'loccitane-pataua-serum-calmante-couro-50ml',
  'loccitane-pataua-serum-calmante-couro-50ml',
  'L''Occitane au Brésil',
  'Sérum Calmante Capilar Patauá+ Cuidado com Couro',
  'scalp',
  '50 ml',
  null,
  50.99,
  'BRL',
  'L''Occitane au Brésil',
  'https://br.loccitaneaubresil.com/pt-br/p/serum-pataua-50ml/BROBVS100671.html',
  '2026-09-29',
  'Aqua/Water; Glycerin; Alcohol; PEG-40 Hydrogenated Castor Oil; Alpha-Glucan Oligosaccharide; Oenocarpus Bataua Acid; Zinc PCA; Menthol; Panthenol; Caprylyl Glycol; Xanthan Gum; Ethylhexylglycerin; Citric Acid; Biosaccharide Gum-1; Sodium Levulinate; Glyceryl Caprylate; Sodium Hydroxide; Sodium Benzoate; Tocopheryl Acetate; Tocopherol; Parfum/Fragrance; Benzyl Salicylate; Limonene; Linalool; Hexyl Cinnamal; Alpha-Isomethyl Ionone; Citronellol; P-Anisic Acid; Geraniol',
  array['scalp_dryness_support', 'moisture_support'],
  'active',
  'https://br.loccitaneaubresil.com/pt-br/p/serum-pataua-50ml/BROBVS100671.html',
  '2026-09-29',
  'editorial'
),
(
  'match-agente-antioleosidade-tonico-100ml',
  'match-agente-antioleosidade-tonico-100ml',
  'Match.',
  'Tônico Capilar Antiefeito Rebote Agente Antioleosidade',
  'scalp',
  '100 ml',
  null,
  104.90,
  'BRL',
  'O Boticário',
  'https://www.boticario.com.br/tonico-capilar-antiefeito-rebote-match-agente-antioleosidade-100ml',
  '2026-09-29',
  'Água; Crospolímero de dimeticona/vinil dimeticona; Dióxido de silício; Extrato do fruto de Cucumis sativus; Pidolato de zinco; Perfume; Butilenoglicol; Álcool benzílico; Fenoxietanol; Edetato dissódico; Crospolímero de acrilatos/acrilato de alquila C10-30; Trolamina; Glicerol; Sorbato de potássio; Benzoato de sódio; Alfa-isometil ionona; Citral; Citronelol; Cumarina; Geraniol; Hexil cinamal; Limoneno; Linalol',
  array['scalp_oiliness_support'],
  'active',
  'https://www.boticario.com.br/tonico-capilar-antiefeito-rebote-match-agente-antioleosidade-100ml',
  '2026-09-29',
  'editorial'
)
on conflict (id)
do update set
  slug = excluded.slug,
  brand = excluded.brand,
  name = excluded.name,
  category = excluded.category,
  size = excluded.size,
  price = excluded.price,
  currency = excluded.currency,
  retailer = excluded.retailer,
  product_url = excluded.product_url,
  price_checked_at = excluded.price_checked_at,
  ingredients_raw = excluded.ingredients_raw,
  attributes = excluded.attributes,
  availability = excluded.availability,
  source_url = excluded.source_url,
  verified_at = excluded.verified_at,
  link_type = excluded.link_type;
